url: devncode.tech
baseurl: 

# Site settings
title: devncode | we foster other communities
email: devncode17@gmail.com
description: "devncode is a platform for fierce minds to share their ideas with others, where you can openly speak about your failures. It’s a platform where you will find all CRAZY AND INSANE programmers and technophiles around you."


# Team names, titles and social links
people:
- name: Muhammad Kamran
  pic: 1
  position: Founder
  social:
    - title: twitter
      url: twitter.com/smkamranqadri
    - title: facebook
      url: facebook.com/devkamran
    - title: linkedin
      url: https://www.linkedin.com/in/muhammad-kamran-qadri-aa720421/

- name: Tehseen Ahmed
  pic: 2
  position: Vice President
  social:
    - title: twitter
      url: https://twitter.com/TehseenSiddiq
    - title: facebook
      url: https://www.facebook.com/tehseen.siddiq
    - title: linkedin
      url: https://www.linkedin.com/in/tehseensiddiq/

- name: Muhammad Usman Farooq
  pic: 3
  position: Public Relation Officer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/munarausmanfarooq/
    - title: github
      url: https://github.com/usmanmunara
    - title: personal
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url: facebook.com/devncode17
  - title: youtube
    url: https://www.youtube.com/channel/UC0_WFaOYjFrZH2zxwI4BZOQ/videos
  - title: medium 
    url: https://medium.com/devncode
  - title: github
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: Offie 94, 7th Floor, Farid Chamber
  - line: Abdullah Haroon Road, Saddar, Karachi, Pakistan

# Build settings
markdown: kramdown
permalink: pretty