url: devncode.tech
baseurl: 

# Site settings
title: devncode | we foster other communities
email: devncode17@gmail.com
description: "devncode is a platform for fierce minds to share their ideas with others, where you can openly speak about your failures. It’s a platform where you will find all CRAZY AND INSANE programmers and technophiles around you."


# Team names, titles and social links
people:
- name: Muhammad Kamran
  pic: 1
  position: Founder
  social:
    - title: twitter
      url: twitter.com/smkamranqadri
    - title: facebook
      url: facebook.com/devkamran
    - title: linkedin
      url: https://www.linkedin.com/in/muhammad-kamran-qadri-aa720421/

- name: Tehseen Ahmed
  pic: 2
  position: Vice President
  social:
    - title: twitter
      url: https://twitter.com/TehseenSiddiq
    - title: facebook
      url: https://www.facebook.com/tehseen.siddiq
    - title: linkedin
      url: https://www.linkedin.com/in/tehseensiddiq/

- name: Muhammad Usman Farooq
  pic: 3
  position: Public Relation Officer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/munarausmanfarooq/
    - title: github
      url: https://github.com/usmanmunara
    - title: user
      url: https://usmanmunara.github.io/     
#Events
events:
- date: "9th December 2017"
  modal-id: 1
  link: "https://www.facebook.com/events/349884418755542/"
  pic: 1
  heading: "devncode meetup IV: Artifical Intelligence"
  class: ""
  description: "Leaving no room for people to stand, this meetup was engaging for the audience as we saw a minimal decrease in the number of attendees after snacks, which is quite rare. The diversity of the tech talks included everything ranging from AI myth busters to the way data is useful in our daily lives"

- date: "4th November 2017"
  pic: 2
  link: "https://www.facebook.com/events/1998879887023825/"
  modal-id: 2
  class: "timeline-inverted"
  heading: "devncode meetup III: IOS & Swift"
  description: "In collaboration with 10Pearls University, this meetup acted as a support for Swift Pakistan. Speakers from Venture Dive, Careem, and other top-notch companies covered basic swift concepts like functional programming in swift to complex concepts like Core Data."
  talk:
    - speaker: "Walid Khan"
      topic: " Intoduction to Swift 4"
      intro: "Senior Software Developer at 10Pearls. Half a dozen year experience in developing Mobile Apps for
            iOS and Android. Madly in love with Swift."
      slides: "https://drive.google.com/open?id=1Wdt2O_dDWt9F6wdHsffXZJH6cLoixNtm"
      videos: " https://www.facebook.com/devncode17/videos/145012429461680/"
      img: 1
    - speaker: "Maroof Khan"
      topic: "Introduction to functional programming in swift"
      intro: "Currently an iOS engineer @ Careem. Have been working on iOS for 2+ years now."
      slides: "https://drive.google.com/open?id=1ibzb234iX8BduJg6LDp_tMPCb3_iMwNj"
      videos: "https://www.facebook.com/devncode17/videos/145022489460674/"
      img: 2
    - speaker: "Muhammad Abdul Subhan"
      topic: "Introduction to CoreGraphics and CoreAnimation"
      intro: "Software Engineer at VentureDive Working on iOS from past 3.5 years"
      slides: "https://drive.google.com/open?id=1e3e5OVNQ5SGtXLMrjTtcj4xKD2lJpfBj"
      videos: "https://www.facebook.com/devncode17/videos/145039856125604/"
      img: 3

- date: "4th October 2017"
  pic: 3
  link: "https://www.facebook.com/events/375886049515592/"
  class: ""
  modal-id: 3
  heading: "devncode meetup II: Server Side programming in Javascript"
  description: "In collaboration with Chainak, we aimed to introduce four new speakers in this event. The event's agenda was to introduce begginers with Node.js and Express.js and let some professionals learn about applications like Socket Chat. "

- date: "26th August 2017"
  pic: 4
  link: "https://www.facebook.com/events/835784043251975/"
  modal-id: 4
  class: "timeline-inverted"
  heading: "devncode meetup I: React Native & Redux"
  description: "This event marked the staring of devncode. Our very first event in collaboration with Facebook Developer Circle - Karachi had huge success. Catering the latest and the most popular Javascript framework, React, we introduced React Native and Redux. "


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url: facebook.com/devncode17
  - title: youtube
    url: https://www.youtube.com/channel/UC0_WFaOYjFrZH2zxwI4BZOQ/videos
  - title: medium 
    url: https://medium.com/devncode
  - title: github
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: Offie 94, 7th Floor, Farid Chamber
  - line: Abdullah Haroon Road, Saddar, Karachi, Pakistan

# Build settings
markdown: kramdown
permalink: pretty